apiVersion: v1
kind: Secret
metadata:
  name: aam
type: Opaque
stringData:
  database-user: aam
  database-password: aam
  database-name: aam
  database-url: postgresql+psycopg://aam:aam@aam-postgres:5432/aam
  secret-key: replace-this-in-production
