apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: aam-api
    newName: localhost/aam-api
    newTag: latest
  - name: aam-ui
    newName: localhost/aam-ui
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: aam-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: aam-worker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: aam-scheduler
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: aam-ui
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Route
      name: aam
    patch: |-
      - op: add
        path: /spec/host
        value: aam.apps.crc.testing
